export const data = {
    categories: [
        { name: 'Car for sale', value: '1', guid: '01', image: require('../assets/images/car-for-sale-cat.jpg') },
        { name: 'Car parts', value: '2', guid: '02', image: require('../assets/images/car-parts-cat.jpg') },
        { name: 'Scrap parts', value: '3', guid: '03', image: require('../assets/images/scrap-cars-cat.jpg') },
        { name: 'Car Accessoriess', value: '4', guid: '04', image: require('../assets/images/car-accessories-cat.jpg') },
    ],
    carBrands: [
        { id: "1", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "2", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "3", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "4", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "5", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "6", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "7", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "8", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "9", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "10", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "11", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "12", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "13", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "14", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "15", name: 'Toyota', image: require('../assets/images/carbrand.png') },
        { id: "16", name: 'Toyota', image: require('../assets/images/carbrand.png') },
    ],
    BrandModels: [
        { id: "1", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "2", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "3", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "4", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "5", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "6", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "7", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "8", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "9", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "10", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "11", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "12", name: 'Corolla', image: require('../assets/images/carbrand.png') },
        { id: "13", name: 'Corolla', image: require('../assets/images/carbrand.png') },
    ],
    Years: [
        { id: "1", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "2", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "3", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "4", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "5", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "6", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "7", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "8", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "9", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "10", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "11", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "12", name: '1995', image: require('../assets/images/carbrand.png') },
        { id: "13", name: '1995', image: require('../assets/images/carbrand.png') },
    ],
    CarCondition: [
        { id: "1", name: 'New', image: require('../assets/images/carbrand.png') },
        { id: "2", name: 'Used', image: require('../assets/images/carbrand.png') },
    ],
    KiloMeter: [
        { id: "1", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "2", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "3", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "4", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "5", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "6", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "7", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "8", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "9", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "10", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "11", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "12", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
        { id: "13", name: '0 To 9999', image: require('../assets/images/carbrand.png') },
    ]
}